routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    abort,
    send_from_directory,
)
from werkzeug.utils import secure_filename
from models.user import User
from models.topic import Topic
from models.reply import Reply
from bson import ObjectId
import os
import uuid

from routes import current_user
from utils import log

main = Blueprint('index', __name__)


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/setting/<string:id>", methods=['POST'])
def setting(id):
    form = request.form
    # 用类函数来判断
    User.update(id,form)
    return redirect(url_for('index.user_detail', id=id))


@main.route("/setting_password/<string:id>", methods=['POST'])
def setting_password(id):
    form = request.form
    u = User.validate_password(form)
    if u is None:
        abort(404)
    else:
        # del form['old_pass']
        User.update_password(id,form)
        return redirect(url_for('index.user_detail', id=id))





@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login u', u)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        print('login', session)
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        topic = Topic.all()
        reply = Reply.all()
        t = sorted(topic, key=lambda l: l.updated_time, reverse=True)
        r = sorted(reply, key=lambda s: s.updated_time, reverse=True)
        return render_template('profile.html', user=u, topic=t, reply=r)


def valid_suffix(suffix):
    valid_type = ['jpg', 'png', 'jpeg']
    return suffix in valid_type


@main.route('/image/add', methods=["POST"])
def add_img():
    u = current_user()

    # file 是一个上传的文件对象
    file = request.files['avatar']
    suffix = file.filename.split('.')[-1]
    if valid_suffix(suffix):
        # 上传的文件一定要用 secure_filename 函数过滤一下名字
        # ../../../../../../../root/.ssh/authorized_keys
        # filename = secure_filename(file.filename)
        # 2017/6/14/19/56/yiasduifhy289389f.png
        # import time
        # filename = str(time.time()) + filename
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        file.save(os.path.join('user_image', filename))
        User.update(u.id, dict(
            user_image='/uploads/' + filename
        ))

    return redirect(url_for(".profile"))


# send_from_directory
# nginx 静态文件
@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory('user_image', filename)


@main.route('/user/<string:id>')
def user_detail(id):
    u = User.find(id)
    if u is None:
        abort(404)
    else:
        topic = Topic.all()
        reply = Reply.all()
        t = sorted(topic, key=lambda l: l.updated_time, reverse=True)
        r = sorted(reply, key=lambda s: s.updated_time, reverse=True)
        return render_template('profile.html', user=u, topic=t, reply=r)


@main.route('/user_setting/<string:id>')
def user_setting(id):
    u = User.find(id)
    return render_template('setting.html', user=u)

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *
import json

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    u = current_user()
    board_id = request.args.get('board_id', 'all')
    if board_id == 'all':
        ms = Topic.all()
    else:
        ms = Topic.find_all(board_id=board_id)

    # if r.exists(board_id):
    #     log('hit redis')
    #     json_string = r.get(board_id)
    #     json_list = json.loads(json_string)
    # else:
    #     print('not hit redis')
    #     json_list = []
    #     for m in ms:
    #         j = m.json()
    #         j['replies'] = m.replies()
    #         j['user_image'] = m.user().user_image
    #         json_list.append(j)
    #     json_string = json.dumps(json_list)
    #     r.set(board_id, json_string)
    # ms = json_list

    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, u=u)


@main.route('/<string:id>')
def detail(id):
    m = Topic.find(id)
    # 传递 topic 的所有 reply 到 页面中
    bs = Board.all()
    return render_template("topic/detail.html", topic=m, bs=bs)


@main.route("/add", methods=["POST"])
# @login_required
@csrf_required
def add():
    form = request.form
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


@main.route("/delete")
@csrf_required
def delete():
    id = request.args.get('id')
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = request.args.get('board_id')
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="注册">
        </div>
    </form>
    <form class="form-horizontal" method="post" action="{{ url_for('.login') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="登录">
        </div>
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/index.min.bdd5dd43.min.css">
    <title>profile</title>
</head>
<body>
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='brand' href='/'>

          <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg" />

      </a>

      <form id='search_form' class='navbar-search' action="/search">
        <input type='text' id='q' name='q' class='search-query span3' value=''/>
      </form>
      <ul class='nav pull-right'>
        <li><a href='/topic'>首页</a></li>

        <li>
            <a href='/mail'>

              未读消息
            </a>
        </li>

        <li><a href='/index'>注册登录</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/setting'>设置</a></li>
        <li>
          <a href='/signout' data-method="post" rel="nofollow">退出</a>
        </li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>

<div id="main">

  <div id="sidebar">

    <div class="panel">
      <div class="header">
        <span class="col_fade">个人信息</span>
      </div>

      <div class="inner">
      <div class="user_card">
      <div>
        <a class="user_avatar" href="{{ url_for('index.user_detail', id=user.id) }}">
          <img src="{{user.user_image}}" >
        </a>
        <span class="user_name"><a class="dark" href="{{ url_for('index.user_detail', id=user.id) }}">{{ user.username }}</a></span>
        <div class="space clearfix"></div>
        <span class="signature">
          “

              {{user.signature}}

          ”
        </span>
      </div>
      </div>



      </div>
    </div>

  </div>

  <div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href="{{ url_for('index.user_detail', id=user.id) }}">主页</a><span class="divider">/</span></li>
        <li><a href="{{ url_for('index.user_setting', id=user.id) }}">设置</a><span class="divider">/</span></li>
        <li><a href='/mail'>消息</a><span class="divider">/</span></li>
      </ul>
    </div>

    <div class="inner userinfo">
      <div class="user_big_avatar">
        <img src="{{user.user_image}}" class="avatar">
      </div>
      <a class="dark">{{ user.username }}</a>
      <p class="col_fade">注册时间 {{ user.ct}}</p>

    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">最近创建的话题</span>
    </div>
    {% for r in topic %}
      {% if r.user_id == user.id %}
          {% set t = r %}

          <div class="cell">
            <a class="user_avatar pull-left" href="{{ url_for('index.user_detail', id=user.id) }}">
              <img src="{{user.user_image}}">
            </a>

            <span class="reply_count pull-left">
              <span class="count_of_replies" title="回复数">
                    {{ t.replies() | count }}
              </span>
              <span class="count_seperator">/</span>
              <span class="count_of_visits" title="点击数">
                    {{ t.views }}
              </span>
            </span>

            <a class="last_time pull-right" href="{{ url_for('topic.detail', id=t.id) }}">
              <img class="user_small_avatar" src="{{user.user_image}}">
              <span class="last_active_time">{{t.ct}}</span>
            </a>

            <div class="topic_title_wrapper">

              <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}" >
                    {{ t.title }}
              </a>
            </div>
          </div>
      {% endif %}
    {% endfor %}

    <!--<div class="cell more">-->
      <!--<a class="dark" href="https://cnodejs.org/user/atian25/topics">查看更多»</a>-->
    <!--</div>-->

  </div>



  <div class="panel">
    <div class="header">
      <span class="col_fade">最近参与的话题</span>
    </div>
    {% for i in reply %}
      {% if i.user_id == user.id %}
        {% set r = i %}
        {% for s in topic %}
          {% if s.id == r.topic_id %}
          {% set t = s %}
            <div class="cell">

              <a class="user_avatar pull-left" href="{{ url_for('topic.detail', id=t.id) }}">
                <img src="{{t.user().user_image}}" >
              </a>

              <span class="reply_count pull-left">
                <span class="count_of_replies" title="回复数">
                      {{ t.replies() | count }}
                </span>
                <span class="count_seperator">/</span>
                <span class="count_of_visits" title="点击数">
                      {{ t.views }}
                </span>
              </span>


              <a class="last_time pull-right" href="{{ url_for('topic.detail', id=t.id) }}">
                <img class="user_small_avatar" src="{{user.user_image}}">
                <span class="last_active_time">{{t.ct}}</span>
              </a>



              <div class="topic_title_wrapper">
                <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}" title="{{t.title}}">
                  {{t.title}}
                </a>
              </div>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    <!--<div class="cell more">-->
      <!--<a class="dark" href="https://cnodejs.org/user/atian25/replies">查看更多»</a>-->
    <!--</div>-->

  </div>



  <div class="panel">
    <div class="header">
      <span class="col_fade">上传头像</span>
    </div>
    <div class="cell">
      <form method=post
            action='{{ url_for(".add_img") }}'
            enctype=multipart/form-data>
          <input type=file name=avatar>
          <!--<input type=submit value=Upload>-->
          <button type="submit">Upload</button>

      </form>
    </div>

  </div>
</div>



</div>




</body>
</html>

templates/setting.html
<!DOCTYPE html>
<!-- saved from url=(0027)https://cnodejs.org/setting -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/index.min.bdd5dd43.min.css">
    <title>setting</title>
</head>
<body>
<!-- navbar -->
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
        <a class='brand' href='/'>

          <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg" />

        </a>

      <form id="search_form" class="navbar-search" action="https://cnodejs.org/search">
        <input type="text" id="q" name="q" class="search-query span3" value="">
      </form>
      <ul class="nav pull-right">
        <li><a href='/topic'>首页</a></li>

        <li>
            <a href='/mail'>

              未读消息
            </a>
        </li>

        <li><a href='/'>注册登录</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/setting'>设置</a></li>
        <li>
          <a href='/signout' data-method="post" rel="nofollow">退出</a>
        </li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>
<div id="main">
   <div id="sidebar">

    <div class="panel">
      <div class="header">
        <span class="col_fade">个人信息</span>
      </div>

      <div class="inner">
      <div class="user_card">
      <div>
        <a class="user_avatar" href="{{ url_for('index.user_detail', id=user.id) }}">
          <img src="{{user.user_image}}" >
        </a>
        <span class="user_name"><a class="dark" href="{{ url_for('index.user_detail', id=user.id) }}">{{ user.username }}</a></span>
        <div class="space clearfix"></div>
        <span class="signature">
          “

              {{user.signature}}

          ”
        </span>
      </div>
      </div>



      </div>
    </div>

  </div>


<div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href="{{ url_for('index.user_detail', id=user.id) }}">主页</a><span class="divider">/</span></li>
        <li><a href="{{ url_for('index.user_setting', id=user.id) }}">设置</a><span class="divider">/</span></li>
        <li><a href='/mail'>消息</a><span class="divider">/</span></li>
      </ul>
    </div>
    <div class="inner">
      
      
      <form id="setting_form" class="form-horizontal" action="{{ url_for('index.setting', id = user.id)  }}" method="post">
        <div class="control-group">
          <label class="control-label">用户名</label>

          <div class="controls">
            <input type="text" class="input-xlarge" name="username" value="{{user.username}}">
          </div>
        </div>

        <div class="control-group">
          <label class="control-label" for="signature">个性签名</label>

          <div class="controls">
            <textarea class="input-xlarge" id="signature" name="signature" size="30"></textarea>
          </div>
        </div>
        <!--<input type="hidden" id="action" name="action" value="change_setting">-->
        <!--<input type="hidden" name="_csrf" value="eHnT7QO2-Wx2_KR5OYpAehv3-r_7tmCbe6D0">-->

        <div class="form-actions">
          <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
        </div>
      </form>
    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">更改密码</span>
    </div>
    <div class="inner">
      <form id="change_pass_form" class="form-horizontal" action="{{ url_for('index.setting_password', id = user.id)  }}" method="post">
        <div class="control-group">
          <label class="control-label" for="old_pass">当前密码</label>

          <div class="controls">
            <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="new_pass">新密码</label>

          <div class="controls">
            <input class="input-xlarge" type="password" id="new_pass" name="password" size="30">
          </div>
        </div>
        <input type="hidden" id="action" name="action" value="change_password">
        <input type="hidden" name="_csrf" value="eHnT7QO2-Wx2_KR5OYpAehv3-r_7tmCbe6D0">

        <div class="form-actions">
          <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
        </div>
      </form>
    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">上传头像</span>
    </div>
    <div class="cell">
      <form method=post
            action='{{ url_for(".add_img") }}'
            enctype=multipart/form-data>
          <input type=file name=avatar>
          <!--<input type=submit value=Upload>-->
          <button type="submit">Upload</button>

      </form>
    </div>

  </div>
</div>

</div>


</body></html>