models/topic.py
from models import Model
from models.user import User
from utils import formatted_time
import time


class Topic(Model):
    @classmethod
    def valid_names(cls):
        names = super().valid_names()
        names = names + [
            ('views', int, 0),
            ('title', str, ''),
            ('content', str, ''),
            ('user_id', str, 0),
            ('board_id', str, 0),
            ('ct', str, formatted_time(int(time.time()))),
        ]
        return names

    @classmethod
    def find(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m

    def user(self):
        u = User.find(id=self.user_id)
        return u

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.mail import Mail
from routes import *

from models.reply import Reply
from utils import log

main = Blueprint('reply', __name__)


def users_from_content(content):
    # 不能解决 @在文本中间 比如 123@name abc，这样就不能获得name了
    parts = content.split(' ')
    users = []
    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.find_by(username=username)
            users.append(u)
    return users


def send_mails(sender, receivers, content):
    for r in receivers:
        form = dict(
            title='你被 {} AT 了'.format(sender.username),
            content=content,
            sender_id=sender.id,
            receiver_id=r.id,
        )
        m = Mail.new(form)
        log(m)


@main.route("/add", methods=["POST"])
def add():
    log('reply add')
    form = request.form
    u = current_user()
    # 发邮件
    log('before send mail', form)
    content = form['content']
    log('reply', content)
    users = users_from_content(content)
    log('reply', users)
    send_mails(u, users, content)
    log('after send mail')
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *
import json

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    u = current_user()
    board_id = request.args.get('board_id', 'all')
    if board_id == 'all':
        ms = Topic.all()
    else:
        ms = Topic.find_all(board_id=board_id)

    # if r.exists(board_id):
    #     log('hit redis')
    #     json_string = r.get(board_id)
    #     json_list = json.loads(json_string)
    # else:
    #     print('not hit redis')
    #     json_list = []
    #     for m in ms:
    #         j = m.json()
    #         j['replies'] = m.replies()
    #         j['user_image'] = m.user().user_image
    #         json_list.append(j)
    #     json_string = json.dumps(json_list)
    #     r.set(board_id, json_string)
    # ms = json_list

    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, u=u)


@main.route('/<string:id>')
def detail(id):
    m = Topic.find(id)
    # 传递 topic 的所有 reply 到 页面中
    bs = Board.all()
    return render_template("topic/detail.html", topic=m, bs=bs)


@main.route("/add", methods=["POST"])
# @login_required
@csrf_required
def add():
    form = request.form
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


@main.route("/delete")
@csrf_required
def delete():
    id = request.args.get('id')
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = request.args.get('board_id')
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>

</head>
<body>
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='brand' href='/'>

          <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg" />

      </a>

      <form id='search_form' class='navbar-search' action="/search">
        <input type='text' id='q' name='q' class='search-query span3' value=''/>
      </form>
      <ul class='nav pull-right'>
        <li><a href='/topic'>首页</a></li>

        <li>
            <a href='/mail'>

              未读消息
            </a>
        </li>

        <li><a href='/'>注册登录</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/setting'>设置</a></li>
        <li>
          <a href='/signout' data-method="post" rel="nofollow">退出</a>
        </li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>
{% block main %}{% endblock %}

{% block footer %}{% endblock %}

<div id="sidebar-mask"></div>

</body>
</html>

templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club test</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
{#    <link rel="stylesheet" href="/static/lib/editor/editor.css">#}
{#    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">#}
{#    <script src="/static/lib/jquery-3.0.0.min.js"></script>#}
{#    <script src="/static/lib/markdownit.js"></script>#}
{#    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>#}
{#    <script src="/static/lib/editor/editor.js"></script>#}
{#    <script src="/static/lib/editor/ext.js"></script>#}
    <script src="//cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
    <script src="//cdn.bootcss.com/prism/1.8.0/prism.js"></script>
    <script src="//cdn.bootcss.com/prism/1.8.1/components/prism-python.min.js"></script>
    <link href="//cdn.bootcss.com/prism/1.8.0/themes/prism.css" rel="stylesheet">
</head>
<body>
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='brand' href='/'>

          <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg" />

      </a>

      <form id='search_form' class='navbar-search' action="/search">
        <input type='text' id='q' name='q' class='search-query span3' value=''/>
      </form>
      <ul class='nav pull-right'>
        <li><a href='/topic'>首页</a></li>

        <li>
            <a href='/my/messages'>

              未读消息
            </a>
        </li>

        <li><a href='/getstart'>新手入门</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/setting'>设置</a></li>
        <li>
          <a href='/signout' data-method="post" rel="nofollow">退出</a>
        </li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>

<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于{{topic.ct}}
            </span>
                    <span>
                {% set u = topic.user() %}
                作者
                <a href="{{ url_for('index.user_detail', id=u.id) }}">
                    {{ u.username }}
                </a>
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                <!--来自 问答-->
                {% for b in bs %}
                {% if b.id == topic.board_id%}
                来自 {{b.title}}
                {%endif%}
                {% endfor %}
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>
    </div>

    <br class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
            {% set u = r.user() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <a href="{{ url_for('index.user_detail', id=u.id) }}" class="user_avatar">
                        <img src="{{ u.user_image }}" title="{{ u.username }}"/>
                    </a>
                    <div class='user_info'>
                        <a class='dark reply_author'>
                            {{ u.username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 / {{ loop.length }}楼 •
                            <span class="time">{{r.ct}}</span>
                        </a>
                    </div>
                    <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">{{ r.content|safe}}</div>
                </div>
            </div>
        {% endfor %}


        <!--<pre>  </pre>-->
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <div class='markdown_editor in_editor'>
                    <div class='markdown_in_editor'>
                        <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                        <div class='editor_buttons'>
                            <input type="submit" class='span-primary submit_btn' data-loading-text="回复中" value="回复">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div id="footer">
  <div id="footer_main">
    <div class="links">
      <a class="dark" href="https://cnodejs.org/rss">RSS</a>
      |
      <a class="dark" href="https://github.com/cnodejs/nodeclub/">源码地址</a>
    </div>

    <div class="col_fade">

  <p>CNode 社区为国内最专业的 Node.js 开源技术社区，致力于 Node.js 的技术研究。</p>
  <p>服务器赞助商为
    <a href="http://www.ucloud.cn/?utm_source=zanzhu&amp;utm_campaign=cnodejs&amp;utm_medium=display&amp;utm_content=yejiao&amp;ytag=cnodejs_logo" target="_blank" class="sponsor_outlink" data-label="ucloud_bottom">
      <img src="/user_image/FuIpEaM9bvsZKnQ3QfPtBHWQmLM9" title="ucloud" alt="ucloud" width="92px">
    </a>
  ，存储赞助商为
    <a href="http://www.qiniu.com/?ref=cnode" target="_blank" class="sponsor_outlink" data-label="qiniu_bottom">
      <img src="/user_image/Fg0jtDIcTqVC049oVu5-sn6Om4NX" title="七牛云存储" alt="七牛云存储" width="115px">
    </a>
  ，由<a href="https://alinode.aliyun.com/?ref=cnode" target="_blank" class="sponsor_outlink" data-label="alinode_bottom">
      <img src="/user_image/FpMZk31PDyxkC8yStmMQL4XroaGD" title="alinode" alt="alinode" height="54px" width="166px">
    </a>提供应用性能服务。
  </p>
  <p>新手搭建 Node.js 服务器，推荐使用无需备案的 <a href="https://www.digitalocean.com/?refcode=eba02656eeb3">DigitalOcean(https://www.digitalocean.com/)</a></p>
</div>


  </div>
</div>
    <script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var markContents = function () {
            var contentDivs = es('.markdown-text')
            for (var i = 0; i < contentDivs.length; i++) {
                var contentDiv = contentDivs[i]
                var content = marked(contentDiv.textContent)
                // console.log(content, contentDiv.innerHTML)
                contentDiv.innerHTML = content
            }
        }

        var highlight = function () {
            var code_list = es('pre code')
            for (var i = 0; i < code_list.length; i++) {
                var code = code_list[i]
                code.className = code.className.replace('lang', 'language')
            }
        }

        var __main = function () {
            markContents()
            registerTimer()
            highlight()
        }

        __main()
    </script>
</body>
</html>

templates/topic/index.html
{% extends "topic/base.html" %}
{% block title %}
论坛主页
{% endblock %}
{% block main %}
    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="inner">
                    <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                    <a href="{{ url_for('index.user_detail', id=u.id) }}">
                        <span class="span-success">个人主页</span>
                    </a>

                </div>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                <div class="header">
                    <a href="/topic"
                       class="topic-tab current-tab">
                        全部
                    </a>

                    {% for b in bs %}
                        <a href="/topic?board_id={{ b.id }}"
                           class="topic-tab current-tab">
                            {{ b.title }}
                        </a>
                    {% endfor %}
                </div>
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                            <div class="cell">
                                <div class="topic_title_wrapper">

                                    <a class="user_avatar pull-left">
                                        <img src="{{ t.user().user_image }}" title="avatar"/>
                                    </a>

                                    <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                        {{ t.title }}
                                    </a>
                                    <span>{{ t.replies() | count }} / {{ t.views }}</span>
                                    <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                        删除
                                    </a>

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();

    </script>
{% endblock %}

templates/topic/new.html
{% extends "topic/base.html" %}
{% block main %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
                        <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
                            <span class="tab-selector">选择版块：</span>
                            <select name="board_id" id="board" required>
                                {% for b in bs %}
                                    {% if bid == b.id %}
                                        <option value="{{ b.id }}" selected>{{ b.title }}</option>
                                    {% else %}
                                        <option value="{{ b.id }}">{{ b.title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <div class='markdown_editor in_editor'>
                                <div class='markdown_in_editor'>
                                    <textarea class='editor' name='content' rows='20'
                                              placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                    <div class='editor_buttons'>
                                        <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                               value="提交">
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();
    </script>
{% endblock %}
{% block footer %}
{% endblock %}

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>